### ISSUE TITLE
fileformat screen recording ?

### ISSUE THREAD

**Issue by Vtom007** [cconard96/glpi-screenshot-plugin#52] opened 2024-11-26 14:34 UTC
Hello
I installed this great plugin and wanted to test it. However, when recording the screen I can't load the film into the ticket, the error message "File format not supported" appears.

Please give me feedback

**Comment by cconard96** [comment] 2024-11-26 14:57
Duplicate of #50

**Closed** 2024-11-26 14:57 UTC
Labels: enhancement
