### ISSUE TITLE
Cannot update to version 1.1.5

### ISSUE THREAD

**Issue by jackburton79** [cconard96/glpi-screenshot-plugin#26] opened 2021-11-15 08:00 UTC
Hi,
Cannot update to latest version from marketplace.
I think the release process failed like last time.

**Comment by cconard96** [comment] 2021-11-15 10:32
It did fail again but I manually created the archive before publishing the release. I tested the download link in the plugin XML and it works.
Are there any errors from the marketplace?

**Comment by cconard96** [comment] 2021-11-15 10:46
Please try updating from the marketplace again. Should be fixed now.

**Comment by jackburton79** [comment] 2021-11-15 12:25
File is correctly downloaded in the tmp directory, and it seems to be correct:

group:/usr/local/share/glpi/files/_tmp # tar -tjf glpi-screenshot-v1.1.6.tar.bz2 
screenshot/locales/pt_PT.mo
screenshot/CHANGELOG.md
screenshot/tools/extract_template.sh
screenshot/locales/en_GB.po
screenshot/ajax/config.php
screenshot/locales/pt_BR.po
screenshot/locales/es_ES.po
screenshot/hook.php
screenshot/locales/en_US.po
screenshot/locales/
screenshot/locales/pt_PT.po
screenshot/locales/fr_FR.mo
screenshot/
screenshot/ajax/
screenshot/screenshot.xml
screenshot/tools/
screenshot/inc/migration.class.php
screenshot/locales/ru_RU.mo
screenshot/js/
screenshot/inc/config.class.php
screenshot/ajax/screenshot.php
screenshot/README.md
screenshot/inc/
screenshot/locales/en_GB.mo
screenshot/locales/fr_FR.po
tar: Removing leading `/' from member names
/
screenshot/.devplugin
screenshot/locales/pt_BR.mo
screenshot/locales/screenshot.pot
screenshot/locales/es_ES.mo
screenshot/inc/profile.class.php
screenshot/inc/screenshot.class.php
screenshot/locales/en_US.mo
screenshot/LICENSE
screenshot/setup.php
screenshot/js/screenshot.js
screenshot/locales/ru_RU.po

**Comment by cconard96** [comment] 2021-11-15 12:41
The only thing I can think of is the issue is with me changing it from a zip archive to a tar.bz2. Do you have the bzip PHP extension installed?

**Comment by jackburton79** [comment] 2021-11-15 12:51
It seems it's installed:
i  | php7-bz2                    | bzip2 codec support for PHP

**Comment by jackburton79** [comment] 2021-11-15 12:55
and GLPI says:
bz2 extension is installed

**Comment by cconard96** [comment] 2021-11-15 21:28
I repackaged the archive. It looks like there was a bad file in the original. I had taken the empty archive it made and just manually added the files but I guess it wasn't really empty even when nothing showed in the GUI.
Apparently the action that creates releases hates this plugin. It works for every other plugin I've used it with without issues yet.

Can you try installing it again?

**Comment by jackburton79** [comment] 2021-11-16 12:36
Thanks! It worked fine now.

**Closed** 2021-11-17 10:06 UTC
Labels: bug
